"""initial migration

Revision ID: 34dfd55f6e7a
Revises: None
Create Date: 2015-05-28 18:18:25.732418

"""

# revision identifiers, used by Alembic.
revision = '34dfd55f6e7a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('confirmed_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('answers',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('correct', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_path'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('question_id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('history',
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('correct_answer_id', sa.String(length=64), nullable=True),
    sa.Column('user_answer_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['correct_answer_id'], ['answers.answer_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_answer_id'], ['answers.answer_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['questions.question_id'], ),
    sa.PrimaryKeyConstraint('poll_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('questions')
    op.drop_table('answers')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
